### ISSUE TITLE
ImportError: No module named click

### ISSUE THREAD

**Issue by arowla** [geowurster/NewlineJSON#53]
My first time trying out this library, and just got the following:

```bash
$ pip install newlinejson
$ python -m newlinejson --help
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/home/ec2-user/venv_pgsql/lib/python2.7/site-packages/newlinejson/__main__.py", line 14, in <module>
    import click
ImportError: No module named click
```

A `pip install click` solves the problem. I see that `click` is indeed included in the dependencies in `setup.py`, on master at least. Has the latest version been pushed to PyPI?

**Comment by geowurster** [comment]
@arowla `NewlineJSON` is primarily an I/O library so the CLI is a bonus tool for simple, common format translations, which is why it is only accessed through `python -m` instead of via a standalone utility.  Since the CLI isn't designed to be a core feature, the `click` dependency is optional - installing with `pip install newlinejson[cli]` will bring in the additional dependency.  Depending on your shell, you may have to escape the square brackets.

`pip` isn't very good about advertising this feature, so I'll add a note to the readme.

**Comment by mianqi2016** [comment]
I tried esp-idf on Ubuntu 20.04, when I typed "idf.py menuconfig", I got this prompt:

ImportError: No module named click

I found "click" was really there, and I have run this instruction last time, so I ran these 2 lines again:
./install.sh
. ./export.sh

then, it was OK.
